### ISSUE TITLE
Boiler as Faucet with temperature?

### ISSUE THREAD

**Issue by seydx** [ebaauw/homebridge-otgw#1]
Hey @ebaauw 

I recently discovered your repo and have seen that you also add boilers / thermostats to HomeKit with this plugin

Is it currently possible to create a faucet service with temperature adjustment like here:

https://youtu.be/D6FzNLDbw5Q

I have not yet tried adding the characteristics like CurrentTemperature / TargetTemperature etc from the thermostat to the faucet service, I also found nothing in the Apple HAP documentation or hap-nodejs

**Comment by ebaauw** [comment]
> I recently discovered your repo and have seen that you also add boilers / thermostats to HomeKit with this plugin

I only started working on this plugin very recently.  My goal is to set the domestic hot water comfort mode off automatically, when I'm away or asleep.  My boiler supports three settings for this mode: on, off, or thermostat controlled.  My thermostat only sets it off during the night (actually the sleep time of its schedule) and during holidays.  Also my boiler allows setting the DHW temperature from 40ºC to 65ºC by the thermostat.  My thermostat supports this, albeit hidden somewhere in the installation menu.  The OpenTherm Gateway acts as a thermostat to the boiler, allowing me to override the thermostat settings.

> Is it currently possible to create a faucet service with temperature adjustment like here:

I like the user interface with on/off and (target?) temperature next to each other.  I don't see the current temperature, but the native app changes background colour as the water is reaching the desired temperature, so the device itself supports it.

Of course, the meaning is different for the boiler: it doesn't turn on or off the water, only the comfort mode.

I'm not sure if we can lure the Eve app into displaying temperature history for a _Faucet_ (or _Valve_?) service - I don't think the Eve Aqua supports hot water.  Eve must see a _Thermostat_ service (as exposed by the Eve Thermo) to display thermostat history.

> I also found nothing in the Apple HAP documentation or hap-nodejs

I don't think Apple has updated the non-commercial, publicly available HAP documentation since they first published it.  The _Faucet_ and _Valve_ services are in HAP-NodeJS's [`ServiceTypes.js`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js), which is extracted from the HomeKit Accessory Simulator.  Tian has extracted the newer _Television_ service manually from the HomeKit daemon.

**Comment by seydx** [comment]
Hey @ebaauw 

i figured out how to setup these kind of service, for more info: https://github.com/KhaosT/HAP-NodeJS/issues/665#issuecomment-486519878

Closing this
