### ISSUE TITLE
BAXI RXM

### ISSUE THREAD

**Issue by miguelpruivo** [ebaauw/homebridge-otgw#11]
Hi, I have a BAXI RXM thermostat which is wireless and supports opentherm. I’m a bit confused about how to setup this up.

[This is the thermostat](https://mediacdn.baxi.pt/-/media/inriver-media/baxi-iberia-media/2021/8/26/a00b10c50i64catalog7pt01pdf.pdf?v=1&d=20210826T140409Z). Sorry, the manual is in Portuguese, couldn’t find in English.

I would like to have some lights on how to setup this up. Do I need any kind of additional hardware? From what I can see here, I already have a gateway. How do I integrate this?

Thank you.

**Comment by ebaauw** [comment]
You would have to place the OpenTherm Gateway in between the thermostat’s base unit and the boiler, cutting the wire that connects them.  I don’t see the BAXI RXM listed under the OTGW’s known [thermostats](http://www.otgw.tclcode.com/matrix.cgi#thermostats), though.

Alternatively, you would need a plugin that communicates with the thermostat’s base station over WiFi, using the same API as their app.  I cannot tell from the sheet, but these smart thermostats tend to be cloud based.

**Comment by miguelpruivo** [comment]
@ebaauw from what I understood, this thermostat is purely wireless (no cables attached). It communicates through Wi-Fi (or RF) with the gateway.

I think it uses a REST API to communicate, but I don’t know how to spoof the requests in order to get them.

The BAXI Connect has default integration with IFTT, Google and Alexa. Maybe there is a simple way to integrate those? Check [here](https://ifttt.com/bdrthermeagroup).

I also found [this](http://domaray.com/2021/12/21/termostato-baxi-connect-integracion-en-home-assistant/) which is a similar thermostat integration, but for the HomeAssistant. I cannot understand how it was implemented or/where did he got the endpoints.

**Comment by ebaauw** [comment]
> from what I understood, this thermostat is purely wireless (no cables attached). It communicates through Wi-Fi (or RF) with the gateway.

According to the sheet you linked, the thermostat connects over RF to its gateway (base station), which is wired to the boiler, presumably using the OpenTherm protocol.  You would place the OpenTherm Gateway in between the thermostat’s gateway and the boiler.

> I think it uses a REST API to communicate, but I don’t know how to spoof the requests in order to get them.

The thermostat’s gateway provides access over WiFi, nothing to do with OpenTherm.

> The BAXI Connect has default integration with IFTT, Google and Alexa.

That smells like a cloud-based API, rather than a local API.  Imho this sucks; this is why I got a dumb clock thermostat with my new boiler, instead of a smart thermostat.

> Maybe there is a simple way to integrate those?

Maybe, but for another plugin by someone else.  This plugin is for the OpenTherm gateway.

**Comment by miguelpruivo** [comment]
@ebaauw I'm new to this stuff "thermostat" stuff, so I'm seeking for some help. Thank you for your clarification.

>According to the sheet you linked, the thermostat connects over RF to its gateway (base station), which is wired to the boiler, presumably using the OpenTherm protocol. You would place the OpenTherm Gateway in between the thermostat’s gateway and the boiler.

So does that mean that I need an additional hardware? What solutions would you suggest me here to get a reliable way to integrate this with HomeKit while being able to turn on/off the boiler?

Thank you!

**Comment by ebaauw** [comment]
I don’t recommend anything; I just share what I’m using, and, sometimes, why.  Afaik, there’s three options:
1. Get a thermostat that natively supports HomeKit;
2. Get a thermostat that exposes an API with a corresponding Homebridge plugin;
3. Get an OpenTherm Gateway with Homebridge OTGW.  Yes that’s separate hardware, see the link in the README.

I’m using 3 since most, if not all, thermostats supporting 1 or 2 are cloud-based, and because my apartment was equipped with an OpenTherm boiler and clock thermostat when I bought it.

**Comment by miguelpruivo** [comment]
@ebaauw if I pick 1 or 2, does the boiler have some protocol that supports replacing it? Is just easy as a swap? I thought that each heater would require its own brand thermostat.

**Comment by ebaauw** [comment]
That’s where OpenTherm comes in: its an industry standard for boilers and thermostats to communicate.  Unfortunately, most manufacturers seem to prefer proprietary protocols for their smart thermostats, even thought the boilers still support OpenTherm, next to the proprietary protocol.

**Comment by miguelpruivo** [comment]
@ebaauw still regarding this:

I have [this](https://mediacdn.baxi.pt/-/media/inriver-media/baxi-iberia-media/2021/10/5/a00b10c50i64proinsman102pdf.pdf?v=1&d=20211005T061520Z) gateway [similar to this one](https://www.youtube.com/watch?v=cwLx9P720k4) which also supports wifi.
<img width="556" alt="Captura de ecrã 2022-03-28, às 14 47 58" src="https://user-images.githubusercontent.com/27860743/160412167-46fc2bb3-8289-4843-b576-66a7a7d5183f.png">
 
Do you think that it can be used?
